apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica2-201701029
  labels:
    name: practica2-201701029
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: wurstmeister/kafka
        name: kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        ports:
          - containerPort: 9092

      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181

      - image: edson2021/api_client_grpc_201701029:latest
        name: clientnode
        ports:
        - containerPort: 5000

      - image: edson2021/server_grpc_201701029:latest
        name: producer
        ports:
        - containerPort: 50051

      - image: edson2021/subscribergo:latest
        name: subscriber
        ports:
        - containerPort: 8080
